### ISSUE TITLE
please learn more about this tool

### ISSUE THREAD

**Issue by AntiWarforever** [Freddywhest/SessionConvertor#1]
I have several Pyrogram sessions for airdrop bot and use windscribe vpn
when is turn on vpn my session become corrupt for simultaneously joining with different location but when i use with your bots based on node ( string session ) this was not happening & they would not corrupt
This thing you made really prevent such an incident or I am wrong

**Comment by Freddywhest** [comment]
You can't use Pyrogram sessions with my bots, but with this tool you can convert Pyrogram or Telethon sessions to sessions that can be use with my bots

**Comment by Freddywhest** [comment]
I don't know why you Pyrogram sessions corrupt when you change the vpn, maybe that's how their sessions work
